// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASoVOVYr4tNT_rEKCAYDZRMNfDS1WFVZo',
    appId: '1:277102881445:web:9324fb2c39c16746b63b4c',
    messagingSenderId: '277102881445',
    projectId: 'swifties-technoscape',
    authDomain: 'swifties-technoscape.firebaseapp.com',
    storageBucket: 'swifties-technoscape.appspot.com',
    measurementId: 'G-0MXN275YC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HikD39NZTjb0j1Xc5509J5FlLAzxq3E',
    appId: '1:277102881445:android:48323f44dbe16b07b63b4c',
    messagingSenderId: '277102881445',
    projectId: 'swifties-technoscape',
    storageBucket: 'swifties-technoscape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7KtIsvuV5tBcp9I_4mvirpNetbmhdDmU',
    appId: '1:277102881445:ios:a5842894e639af98b63b4c',
    messagingSenderId: '277102881445',
    projectId: 'swifties-technoscape',
    storageBucket: 'swifties-technoscape.appspot.com',
    iosClientId: '277102881445-3hfv62jufn02skf1m1m90ihacsjpgi69.apps.googleusercontent.com',
    iosBundleId: 'com.swifties.switfiesTechnoscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7KtIsvuV5tBcp9I_4mvirpNetbmhdDmU',
    appId: '1:277102881445:ios:f060b47b2f4eca49b63b4c',
    messagingSenderId: '277102881445',
    projectId: 'swifties-technoscape',
    storageBucket: 'swifties-technoscape.appspot.com',
    iosClientId: '277102881445-bsnoeh4dcre20mt4drbg6r65e3tma7kh.apps.googleusercontent.com',
    iosBundleId: 'com.swifties.switfiesTechnoscape.RunnerTests',
  );
}
